import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <div className='w-full overflow-hidden'>
                    <div className='px-6 flex justify-center items-center'>
                        <div className='xl:max-w-[1280px] w-full'>
                            <Navbar />
                        </div>
                    </div>
                    <div id='home' className='flex justify-center items-start pt-[120px]'>
                        <div className='xl:max-w-[1280px] w-full text-white'>
                            {children}
                        </div>
                    </div>

                </div>
            </body>
        </html>
    )
}
